[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=php-fpm82 -F
autostart=true
autorestart=true

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true

# 让 supervisor 管理 cron
[program:cron]
command=crond -f -L /var/log/cron.log
autostart=true
autorestart=true