name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Docker Hub 用户名
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Docker Hub 密码

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: your-dockerhub-username/my-image:${{ github.sha }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max